version: 0.2

phases:
  install:
    commands:
      # install terraform binary
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - echo 'Build phase'
      - terraform workspace new pipeline
      - terraform -chdir=terraform/$PIPE_NAME init
      - terraform -chdir=terraform/$PIPE_NAME destroy -auto-approve


cache:
  paths:
    - ~/.terraform.d/plugin-cache
