version: 0.2

phases:
  install:
    commands:
      # install terraform binary
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - echo 'Build phase'
      - sed -i 's/replace/$TERRAFORM_WORKSPACE/g' terraform/pipeline/terraform.tfvars
      - terraform workspace new pipeline_$TERRAFORM_WORKSPACE
      - terraform workspace select pipeline_$TERRAFORM_WORKSPACE
      - terraform workspace list
      - terraform -chdir=terraform/$PIPE_NAME init
      - terraform -chdir=terraform/$PIPE_NAME apply -auto-approve


cache:
  paths:
    - ~/.terraform.d/plugin-cache
